# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myInstagram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myInstagram
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
   pod 'Firebase/Storage'
   pod 'Firebase/Messaging'
   pod 'GoogleSignIn'
   pod 'FBSDKLoginKit'
   pod 'Fabric', '~> 1.7.2'
   pod 'Crashlytics', '~> 3.9.3'
   pod 'TWMessageBarManager'
   pod 'FirebaseUI/Storage'
   pod 'SDWebImage'
   pod 'SVProgressHUD'
  target 'myInstagramTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'FirebaseUI/Storage'
  end

end
